# Generated by Django 5.1.2 on 2024-10-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('language', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'indexes': [models.Index(fields=['author'], name='books_book_author_b941fe_idx'), models.Index(fields=['published_date'], name='books_book_publish_649cd8_idx'), models.Index(fields=['language'], name='books_book_languag_ea595e_idx')],
            },
        ),
    ]
